name: 635Proj
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - gensim=3.8.3
  - h5py=2.10.0
  - keras=2.4.3
  - matplotlib=3.3.4
  - nltk=3.5
  - numpy=1.19.5
  - pandas=1.2.2
  - scikit-plot=0.3.7
  - scikit-learn
  - tensorflow-gpu=2.4.1